# Generated by Django 5.2.4 on 2025-08-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ecom", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="type",
            field=models.CharField(
                choices=[
                    ("electronics", "Electronics"),
                    ("clothing", "Clothing"),
                    ("home_appliances", "Home Appliances"),
                    ("books", "Books"),
                    ("toys", "Toys"),
                    ("electronics", "Electronics"),
                    ("clothing", "Clothing"),
                    ("home_appliances", "Home Appliances"),
                    ("books", "Books"),
                    ("toys", "Toys"),
                ],
                default="electronics",
                max_length=50,
            ),
        ),
    ]
